FROM golang:1.26.2-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o relay ./cmd/relay

FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY --from=builder /app/relay .
COPY --from=builder /app/configs ./configs

EXPOSE 443

ENV ZEROLOG_PRETTY=true

ENTRYPOINT ["./relay"]
